### ISSUE TITLE
Html in southern sandstone

### ISSUE THREAD

**Issue by ryecroft** [rockfax/rockfax-digital-package-issues#15]
See email from mark rogerson

**Comment by alanjamesrockfax** [comment]
Can't find a relevant email relating to this from Mark

**Comment by JimBee-JB** [comment]
I think the rogue html was in the crag description for a few Southern Sandstone crags, near the old info about protecting Sandstone. This whole section got overhauled in v3.6.3 (~Aug 2020 - after the issue was raised) with much more comprehensive info, pretty sure the rogue code got resolved then. I suspect that this can be closed. Just had a look at a few of the main crags today and the description text is fine.
